name = "artemis-api"
main = "src/index.ts"
compatibility_date = "2026-04-01"
workers_dev = true

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "ARTEMIS_KV"
id = "81774a0a72994d188ce5b0e3e23a812e"

[[durable_objects.bindings]]
name = "POLLER"
class_name = "DsnPoller"

[[migrations]]
tag = "v1"
new_classes = ["DsnPoller"]
